### PR TITLE
Allow globs as part of image param for `out`

### PR DESCRIPTION
**Pull request by kkallday**
Co-authored-by: Edwin Xie <exie@pivotal.io>

### CODE REVIEW

**Comment by kkallday** [comment]
Hi all,

This PR has been red in CI for a little bit. I just fixed it this morning. Just wanted to bring attention to it again.

cc @pivotal-jamie-klassen @vito

**Comment by kkallday** [comment]
Hey @vito. When do you plan to release the next version including this change set?

**Comment by vito** [comment]
@kkallday https://github.com/concourse/registry-image-resource/releases/tag/v0.8.0

**Comment by kkallday** [comment]
@vito when I don't specify the resource type, I expected it to pull latest but I noticed the new feature is not in that build. When I specify:
```
- name: registry-image
  source:
    repository: concourse/registry-image-resource
  type: docker-image
```
It pulls the latest and the feature is include. My question is: when I don't specify the resource type, what version of the resource is being used?

**Comment by vito** [comment]
@kkallday It depends on your Concourse version, so I can't really give you a straight answer. Right now they're bumped automatically so you could have to see which `registry-image` resource version was shipped prior to your Concourse version.

**Comment by kkallday** [comment]
@vito got it. So when I don't put the resource type in the pipeline definition, it is probably using the `registry-image` resource that is bundled in the version of Concourse I am using?

**Comment by vito** [comment]
@kkallday yep, definitely. All resource types either come from the pipeline or prepackaged with Concourse onto your workers.

**Pull request merged**
