### PR TITLE
feat: Add the ability to monitor a registry with a tag filter

### PR DESCRIPTION
**Pull request by jghiloni**
Somewhat related to the conversation(?) in #151, this PR provides the pipeline author a way to monitor a registry image for new tags, and to use that for the get criterion. This has been tested against public and private repos.

### CODE REVIEW

**Comment by jghiloni** [comment]
Let's call this WIP for now -- I realized this doesn't help for anything other than check scripts, I want to be able to handle pinning, as well as adding the tag to the in metadata

**Comment by vito** [comment]
@jghiloni Just FYI, #151 has been on my weekend to-do list for a while so I'm taking a swing at it now! Just thought I'd ping in case you had also started looking into it beyond what's done here so far. Happy to hold off if you are.

**Comment by jghiloni** [comment]
Nope, go ahead! This has had to take a backseat.

**Comment by vito** [comment]
@jghiloni #214 is just about ready if you'd like to take a look! Curious to know whether the semver pattern matches your use case.

**Comment by jghiloni** [comment]
It's exactly our use case, would love to give it a shot when you get a chance.

**Pull request closed without merging**
