### PR TITLE
Upgrade to latest notary-gcr

### PR DESCRIPTION
**Pull request by jertel**
Upgrading to the latest notary-gcr dependency enables the ability to sign images on Docker Hub's notary service. Also clarify signing config instructions in README.

See https://github.com/simonshyu/notary-gcr/pull/9 for more information.

### CODE REVIEW

**Comment by TOoSmOotH** [comment]
This works great

**Comment by cirocosta** [comment]
Hey @TOoSmOotH @jertel , sorry for the long delay! 

I wanted to better understand how to test this feature out before getting it in (and perhaps think about signing `concourse/concourse` images too?), would you have any good resources that I could go over to get greater knowledge about it?

Also, the README seems to be very directed towards DockerHub - is that because the implementation is specific to the way that DockerHub handles TUF (please correct me if TUF is unrelated)? 

thank you!

**Comment by jertel** [comment]
Hey @cirocosta, 

The changes pushed to notary-gcr, which I'm requesting be pulled into registry-image-resource are specific to Docker Hub. There had supposedly already been support in this resource for signing some registries, so these changes _add_ support to also include Docker Hub, since Docker Hub requires the repository/registry paths and TUF values be specified in a way that the existing registry-image-resource couldn't handle. The instructions added to the notary-gcr README assumes you already have setup your Docker Hub repository to support image signing. If that hasn't yet been done you can review [Docker's Documentation on Image Signing](https://docs.docker.com/ee/dtr/user/manage-images/sign-images/) to get your repository setup. There's a lot of text in the docs but it's really not that involved. If you can generate private keys (ex: openssl) and run `docker trust ...` commands against the Concourse public repos then you have all you need to do this.

Signing the Concourse images would be a wise move, though it's useful to note that by default `docker pull` doesn't require images to be signed. I don't know enough about the Concourse container management subsystem to comment on whether it already supports the ability to require images be signed.

**Comment by xtreme-sameer-vohra** [comment]
Hey @jertel 
Thanks for submitting the PR. Please excuse the delay in reviewing it.
 I am going to be reviewing it shortly. Please just bear with me as I am unfamiliar with the Docker Notary service and how to do acceptance testing on this PR.

**Comment by jertel** [comment]
Thanks for the update. I've resolved the latest merge conflicts.

**Comment by xtreme-sameer-vohra** [comment]
Thanks @jertel 

Here is what I found testing out the feature;
- `out` based on your instructions and [this guide](https://marcofranssen.nl/signing-docker-images-using-docker-content-trust/) I was able to validate publishing an image with DCT.
- `check` and `in` behaviour didn't change based on configuring the DCT specific params. In other words, I was able to pull a non-securely signed tag with the DCT specific values configured. Is that what you had expected to happen ? Manually setting `export DOCKER_CONTENT_TRUST=1` didn't have any impact.

**Comment by jertel** [comment]
That's correct, only _out_ is affected by this PR. I'm not sure that _check_ or _in_ were ever coded to support strict signing requirements. I think that would be a good idea to support it but that's not in the scope of this PR.

This _out_ function serves a publication purpose: to publish my signed images to Docker Hub, for public consumption. These images I'm publishing are not intended to be used by Concourse pipelines, but rather are the build artifacts for my end-user product.

**Comment by xtreme-sameer-vohra** [comment]
Thanks for the PR and the README update as well @jertel !

**Pull request merged**
