### PR TITLE
Upgrade github.com/simonshyu/notary-gcr

### PR DESCRIPTION
**Pull request by SimonXming**
* Upgrade github.com/simonshyu/notary-gcr to support `ContentTrust.Scopes` and `ContentTrust.Username/Password`

### CODE REVIEW

**Comment by evanchaoli** [comment]
Code change looks good to me. I think we should update README.md:

1. 3 new parameters added to `trust_content`
2. Add some note for "only put support signing"

**Comment by xtremerui** [comment]
Is there any more changes? I dont see `Add some note for "only put support signing"` yet.

**Comment by evanchaoli** [comment]
> Is there any more changes? I dont see `Add some note for "only put support signing"` yet.

That has been mentioned in README: 

https://github.com/concourse/registry-image-resource/blob/671c7bcae57f48111cd7fd755eea7b72553fb44f/README.md?plain=1#L274

**Review by xtremerui — APPROVED** [review]
LGTM! Thx.

**Pull request merged**
